%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 535.4 
Camera1.fy: 539.2
Camera1.cx: 320.1
Camera1.cy: 247.6

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 640
Camera.height: 480

# Tracking parameters 
Track.noise_input: 1

Env.Trajectory.radius: 3
Env.Map.env_width: 9    # 
Env.Map.env_height: 4
Env.Map.env_length: 9

# results_path 
Evaluation.result_path: "../evaluation/baseline_test/"

# Camera frames per second 
Camera.fps: 30