%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 481.20 
Camera1.fy: -480.0
Camera1.cx: 319.50
Camera1.cy: 239.50

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 752
Camera.height: 480

Camera.newWidth: 600
Camera.newHeight: 350

# Tracking parameters 
Track.noise_input: 1
# Dataset

Env.Trajectory.radius: 5
Env.Map.env_width: 11
Env.Map.env_height: 8
Env.Map.env_length: 7

Env.ReadOpenStructure.bool: 1
Env.Public.envtraj_path: "../../dataset/1002/datasets/lrkt0/camera_poses.txt"
Env.Public.envpoint_path: "../../dataset/1002/datasets/lrkt0/point_landmarks.txt" #results/V103/3DMap_registered.txt"
Env.Public.envline_path: "../../dataset/1002/datasets/lrkt0/line_landmarks.txt"
Env.Public.associate_path: "../../dataset/1002/datasets/lrkt0/association.txt"

Env.Public.envtraj_num: 633
Env.Public.envpoint_num: 2560
Env.Public.envline_num: 102

# results_path 
Evaluation.result_path: "../evaluation/icl_test/"

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.0747

# Depth map values factor
RGBD.DepthMapFactor: 5000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0